### ISSUE TITLE
Add babel into testing tasks

### ISSUE THREAD

**Issue by dmaloneycalu** [vokal/dominatr-grunt#27]
@vokal/web 
- Browserstack only supports testing up to Chrome v44
- ES6 arrow functions are available in v45
- Babel needs run prior to testing
- existing `grunt-babel` task only targets concatenated project file (not source files used in testing)
- `grunt-babel` does not support replace option to glob match modules directory

Discussions leading up to this can be found [here](https://github.com/vokal/HelloTruly-Admin/pull/21#issuecomment-139405550) and [here](https://github.com/vokal/dominatr-grunt/pull/26)

**Comment by dmaloneycalu** [comment]
@jrit this should be ready to be closed (also @Deanzie since this describes what that `=>` problem was)

**Comment by jrit** [comment]
Totes
