### ISSUE TITLE
Remove 'instructed' files after running tests that fail

### ISSUE THREAD

**Issue by dmaloneycalu** [vokal/dominatr-grunt#28]
When running 'npm test' and a test fails, the 'instructed' files are not removed. It's been causing some minor irritation because changing files does not immediately take effect locally.

Thoughts on doing this are welcome. Flat out adding a force setting to it would affect it's use in Drone.

**Comment by Tathanen** [comment]
How will the files be reverted to their development state after running tests if not by calling envDontUseSource and buildCore again?

**Comment by dmaloneycalu** [comment]
@Tathanen I wanted to propose using a temp directory for testing instead of overwriting the build directory

**Comment by dmaloneycalu** [comment]
@jrit this should be ready to be closed

**Comment by jrit** [comment]
agreed
