### ISSUE TITLE
changing index.html doesn't cause browser livereload

### ISSUE THREAD

**Issue by dmaloneycalu** [vokal/dominatr-grunt#39]
`grunt watch` runs the `copy:index` task, but does not cause a browser to reload afterwards

**Comment by jrit** [comment]
This is working on my machine. I'm not sure if it was fixed or just wasn't an issue on Windows to start with. @dmaloneycalu can you confirm?

**Comment by dmaloneycalu** [comment]
I've noticed a few inconsistent episodes where a saved file doesn't cause a refresh, but otherwise working fine. Probably good to close this.
