### ISSUE TITLE
Build favicons into root directory

### ISSUE THREAD

**Issue by Tathanen** [vokal/dominatr-grunt#59]
Generally agreed upon as best practice, we don't do it cause it's messy looking, but if grunt is moving the files from `source/favicon/` to `build/` for us who cares really.

Some context: https://realfavicongenerator.net/faq#why_icons_in_root

Wanted to create an issue before just doing it, to make sure people were on board. @vokal/web

**Comment by jrit** [comment]
Seems fine if the source files are still contained neatly.
